apiVersion: v1
kind: Pod
metadata:
  name: news-database
  labels:
    app: news-database
spec:
  containers:
    - name: news-database-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "Password123!@"
        - name: "MYSQL_DATABASE"
          value: "empresa"
        - name: "MYSQL_PASSWORD"
          value: "Password123!"